development:
  adapter: postgresql
  database: superdriver_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: superdriver_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: superdriver_production
  pool: 5
  timeout: 5000